modLoader="javafml"
loaderVersion="[43,)"
license="GPL"
issueTrackerURL="https://github.com/MommyHeather/betonquest-gui-1.19.4/"

[[mods]]
modId="betonquestgui"
version="${mod_version}"
displayName="BetonQuest GUI"
authors="MommyHeather, Giovanni Bozzano, Domenico De Luca"
description="A GUI for BetonQuest"

[[dependencies.betonquestgui]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betonquestgui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"
